linters-settings:
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  staticcheck:
    enabled: true
  misspell:
    enabled: true

run:
  skip-dirs:
    - vendor
    - node_modules
