linters-settings:
  enable-all: true
  disable:
    - exhaustive
    - wsl
    - gocritic
    - interfacer
    - megacheck
    - revive
    - govet
    - errcheck
    - lll

run:
  tests: true
  skip-dirs-use-default: true
  issues-exit-code: 1

linters:
  enable:
    - deadcode
    - errcheck
    - golint
    - govet
    - maligned
    - megacheck
    - misspell
    - unconvert
    - gofmt
    - gocyclo
    - goimports
    - lll
    - prealloc
    - stylecheck
    - structcheck
    - varcheck
