name: GoLint and Email

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GolangCI-Lint
        uses: golangci/run-golangci-lint@v1
        with:
          version: v4.0.0
          args: run ./...
          config: .golangci.yml

  send_email:
    name: Send email notification
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtps://raphaelevaan1%40gmail.com:yhllwyxkuoqxkscr@smtp.gmail.com
          subject: 'Test'
          to: 'if-21053@students.ithb.ac.id'
          from: 'raphaelevaan1@gmail.com'
          body: 'Ini adalah percobaan untuk tugas.'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
