name: Send Email on Push

on:
  push:
    branches:
      - main

jobs:
  send_email:
    name: Send email notification
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtps://raphaelevaan1%40gmail.com:yhllwyxkuoqxkscr@smtp.gmail.com
          subject: 'Test'
          to: 'if-21053@students.ithb.ac.id'
          from: 'raphaelevaan1@gmail.com'
          body: 'Ini adalah percobaan untuk tugas.'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
